"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](blue)\
$os\
$username\
[](bg:lavender fg:blue)\
$directory\
[](bg:yellow fg:lavender)\
$git_branch\
$git_status\
[](bg:green fg:yellow)\
$nodejs\
$rust\
$java\
$kotlin\
$python\
[](bg:sapphire fg:green)\
$cmd_duration\
[](bg:surface0 fg:sapphire)\
$time\
[ ](fg:surface0) """

add_newline = true
palette = 'catppuccin_mocha'

[os]
disabled = false
style = "bg:blue fg:crust"

[os.symbols]
Macos = "󰀵"
Linux = "󰌽"
Arch = "󰣇"
Ubuntu = "󰕈"
Debian = "󰣚"
Fedora = "󰣛"
Windows = ""
Android = ""

[username]
show_always = true
style_user = "bg:blue fg:crust"
style_root = "bg:blue fg:red bold"
format = '[ $user ]($style)'

[directory]
style = "bg:lavender fg:crust"
format = "[ 󰉋 $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Developer" = "󰲋 "
"dev" = "󰲋 "
"Music" = "󰝚 "
"Pictures" = " "

[git_branch]
symbol = " "
style = "bg:yellow fg:crust"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:yellow fg:crust"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = " "
style = "bg:green fg:crust"
format = '[ $symbol$version ]($style)'

[rust]
symbol = " "
style = "bg:green fg:crust"
format = '[ $symbol$version ]($style)'

[java]
symbol = " "
style = "bg:green fg:crust"
format = '[ $symbol$version ]($style)'

[kotlin]
symbol = " "
style = "bg:green fg:crust"
format = '[ $symbol$version ]($style)'

[python]
symbol = " "
style = "bg:green fg:crust"
format = '[ $symbol$version(\($virtualenv\)) ]($style)'

[cmd_duration]
min_time = 500
style = "bg:sapphire fg:crust"
format = '[ 󱎫 $duration ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:surface0 fg:text"
format = '[  $time ]($style)'

[line_break]
disabled = true

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold green)'
vimcmd_replace_one_symbol = '[❮](bold lavender)'
vimcmd_replace_symbol = '[❮](bold lavender)'
vimcmd_visual_symbol = '[❮](bold yellow)'

[gcloud]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
